[book]
authors = ["ZhuoXian Han"]
language = "zh-cn"
multilingual = false
src = "src"
title = "Learning Rust"
description = "Learning Rust Book."

[rust]
edition = "2024"

[build]
create-missing = true

[output.html]
mathjax-support = true
default-theme = "light"
preferred-dark-theme = "navy"
curly-quotes = true
copy-fonts = true
no-section-label = false
git-repository-url = "https://github.com/hanzhuoxian/learning_rust"
git-repository-icon = "fa-github"

[output.html.search]
enable = true
